//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public Nullable<System.DateTime> FechaDev { get; set; }
        public int PrestamoId { get; set; }
        public int EjemplarCodBarras { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
        public virtual Ejemplar Ejemplar { get; set; }
        public virtual Multa Multa { get; set; }
    }
}
